[build]
  functions = "netlify/functions"
  node_bundler = "esbuild"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_OPTIONS = "--enable-source-maps"

[functions.api]
  external_node_modules = ["express"]
  format = "esm"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200